{
 "title": "CyberPower UPS Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "SNMP_Target",
    "label": "SNMP_Target",
    "query": {
     "query": "label_values(ups_battery_status,snmp_target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_status{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  },
  {
   "title": "Output Source",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_output_source{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_voltage{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_output_frequency{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "ups_output_current * ups_output_voltage {snmp_target=\"$SNMP_Target\"}",
     "legendFormat": "VA"
    }
   ]
  },
  {
   "title": "Output Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ups_output_percent_load{snmp_target=\"$SNMP_Target\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Input and Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ups_input_voltage{snmp_target=\"$SNMP_Target\"}",
     "legendFormat": "Input Voltage"
    },
    {
     "expr": "ups_output_voltage{snmp_target=\"$SNMP_Target\"}",
     "legendFormat": "Output Voltage"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ampere" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_output_current{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  },
  {
   "title": "Battery Charge Remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_estimated_charge_remaining{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  },
  {
   "title": "Estimated Minutes Remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_estimated_minutes_remaining{snmp_target=\"$SNMP_Target\"}"
    }
   ]
  }
 ]
}